<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro"> 

    <xacro:property name="base_length" value="1.18" />
    <xacro:property name="base_width" value="0.3" />
    <xacro:property name="base_height" value="0.001" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    
    
    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/urdf/Chassis2.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2}" rpy="0 0 1.57" />
            <material name="green" />
        </visual>

        <collision>
            <geometry>
                <box size="0.35 0.5 0.28" />
            </geometry>
            <origin xyz="0.2 0 0.08" rpy="0 0 1.57" />

        </collision>


        <inertial>
            <mass value="30" />
            <inertia ixx="372139.2" ixy="-347.727" ixz="350.64" iyy="258387.4" iyz="14259.7" izz="447654.2" />
        </inertial>

    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <mesh filename="package://my_robot_description/urdf/rear_wheel.stl" scale="0.001 0.001 0.001" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
                <material name="grey" />
            </visual>


            <collision>
                <geometry>
                    <box size="0.2 0.2 0.2" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>

            <inertial>
                <mass value="1" />
                <inertia ixx="14346.1" ixy="0" ixz="0" iyy="7606" iyz="0" izz="7606" />
            </inertial>

        </link>


    </xacro:macro>

    <xacro:wheel_link prefix="left" />
    <xacro:wheel_link prefix="right" />

    <link name="fourth_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/urdf/front_wheel.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <material name="grey" />
        </visual>


            <collision>
                <geometry>
                    <box size="0.2 0.2 0.2" />
                </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>

        <inertial>
            <mass value="2" />
            <inertia ixx="112.3" ixy="0" ixz="0" iyy="112" iyz="0" izz="197" />
        </inertial>

    </link>


    <link name="fifth_link">
        <visual>
            <geometry>
                <mesh filename="package://my_robot_description/urdf/front_wheel.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <origin xyz="0 0 0" rpy="1.57 0 0" />
            <material name="grey" />
        </visual>



            <collision>
                <geometry>
                    <box size="0.2 0.2 0.2" />
                </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>

        <inertial>
            <mass value="2" />
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
        </inertial>

    </link>



    <link name="base_footprint" />

    <joint name="base_second_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${base_length / 3} ${((base_width) + wheel_length) / 2} 0" rpy="0 0 3.14" />
        <axis xyz="0 -1 0" />
    </joint>  

    <joint name="second_third_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${base_length / 3} ${(-(base_width) - wheel_length) / 2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_third_joint" type="continuous">
        <parent link="base_link" />
        <child link="fourth_link" />
        <origin xyz="0.089 0.145 -0.05" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>


    <joint name="base_fouth_joint" type="continuous">
        <parent link="base_link" />
        <child link="fifth_link" />
        <origin xyz="0.089 -0.145 -0.05" rpy="3.14 0 0" />
        <axis xyz="0 -1 0" />
    </joint>


    <joint name="base_footprint_base_link" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>

    
</robot>